workflows:
  react-native-ipa:
    name: React Native IPA Build
    environment:
      vars:
        XCODE_WORKSPACE: "ios/YourApp.xcworkspace"
        XCODE_SCHEME: "YourApp"
      ios_signing:
        distribution_type: ad_hoc
        bundle_identifier: "com.seunome.seuapp"
    scripts:
      - name: Install dependencies
        script: |
          npm install
          cd ios
          pod install
          cd ..
      - name: Build .ipa
        script: |
          xcodebuild -workspace $XCODE_WORKSPACE -scheme $XCODE_SCHEME -configuration Release -sdk iphoneos -archivePath $HOME/build/$XCODE_SCHEME.xcarchive archive
          xcodebuild -exportArchive -archivePath $HOME/build/$XCODE_SCHEME.xcarchive -exportOptionsPlist ios/exportOptions.plist -exportPath $HOME/build/ipa
    artifacts:
      - build/ipa/*.ipa 